


CREATE TABLE IF NOT EXISTS `acteur` (
    `NUMERO_ACTEUR` int(11) NOT NULL AUTO_INCREMENT,
    `NOM_ACTEUR` varchar(50) NOT NULL,
    `PRENOM_ACTEUR` varchar(50) NOT NULL,
    `NATION_ACTEUR` varchar(100) NOT NULL,
    `DATE_DE_NAISSANCE` DATE NOT NULL,
    PRIMARY KEY (`NUMERO_ACTEUR`)
) ;

Create TABLE IF NOT EXISTS `role` (
    `NOM_DU_ROLE` varchar(50) NOT NULL,
    `NUMERO_ACTEUR` int(11) NOT NULL,
    `NUMERO_FILM` int(11) NOT NULL,
    PRIMARY KEY (`NUMERO_ACTEUR`, `NUMERO_FILM`)
) ;

CREATE TABLE IF NOT EXISTS `film` (
    `NUMERO_FILM` INT NOT NULL AUTO_INCREMENT,
    `TITRE_FILM` VARCHAR(50) NOT NULL,
    `DATE_DE_SORTIE` DATE NOT NULL,
    `DUREE` INT NOT NULL,
    `GENRE` VARCHAR(50) NOT NULL,
    `REALISER` int NOT NULL,
    PRIMARY KEY (`NUMERO_FILM`)
);

CREATE TABLE IF NOT EXISTS `realisateur` (
    `NUMERO_REALISATEUR` INT NOT NULL AUTO_INCREMENT,
    `NOM_REALISATEUR` VARCHAR(50) NOT NULL,
    `PRENOM_REALISATEUR` VARCHAR(50) NOT NULL,
    `NATION_REALISATEUR` VARCHAR(100) NOT NULL,
    PRIMARY KEY (`NUMERO_REALISATEUR`)
);

CREATE TABLE IF NOT EXISTS `seance` (
    `NUMERO_SEANCE` INT NOT NULL AUTO_INCREMENT,
    `DATE_SEANCE` DATE NOT NULL,
    `HORAIRE` TIME NOT NULL,
    `PROJETER` INT NOT NULL,
    `A_POUR_CATEGORIE` INT NOT NULL,
    PRIMARY KEY (`NUMERO_SEANCE`)
);

CREATE TABLE IF NOT EXISTS `reservation` (
    `NUMERO_SEANCE` INT NOT NULL,
    `NOM_SPECTATEUR` VARCHAR(50) NOT NULL,
    `NUMERO_PLACE` INT NOT NULL
);

CREATE TABLE IF NOT EXISTS `place` (
    `NUMERO_PLACE` int(20) NOT NULL AUTO_INCREMENT,
    `CATEGORIE_DE_LA_PLACE` int NOT NULL,
    PRIMARY KEY (`NUMERO_PLACE`)
);


CREATE TABLE IF NOT EXISTS `categorie_seance` (
    `CATEGORIE_DE_LA_SEANCE` int NOT NULL AUTO_INCREMENT,
    `TYPE_SEANCE` VARCHAR(50) NOT NULL,
    PRIMARY KEY (`CATEGORIE_DE_LA_SEANCE`)
);

CREATE TABLE IF NOT EXISTS `categorie_place` (
    `CATEGORIE_DE_LA_PLACE` int NOT NULL AUTO_INCREMENT,
    `TYPE_PLACE` VARCHAR(50) NOT NULL,
    PRIMARY KEY (`CATEGORIE_DE_LA_PLACE`)
);

CREATE TABLE IF NOT EXISTS `tarif` (
    `TARIF` DOUBLE NOT NULL,
    `CATEGORIE_DE_LA_SEANCE` int(20) NOT NULL,
    `CATEGORIE_DE_LA_PLACE` int(20) NOT NULL,
    PRIMARY KEY (`CATEGORIE_DE_LA_SEANCE`, `CATEGORIE_DE_LA_PLACE`)
);

-- Add all foreign key
ALTER TABLE `role` ADD FOREIGN KEY (`NUMERO_ACTEUR`) REFERENCES `acteur`(`NUMERO_ACTEUR`);
ALTER TABLE `role` ADD FOREIGN KEY (`NUMERO_FILM`) REFERENCES `film`(`NUMERO_FILM`);
ALTER TABLE `film` ADD FOREIGN KEY (`REALISER`) REFERENCES `realisateur`(`NUMERO_REALISATEUR`);
ALTER TABLE `reservation` ADD FOREIGN KEY (`NUMERO_SEANCE`) REFERENCES `seance`(`NUMERO_SEANCE`);
ALTER TABLE `reservation` ADD FOREIGN KEY (`NUMERO_PLACE`) REFERENCES `place`(`NUMERO_PLACE`);
ALTER TABLE `place` ADD FOREIGN KEY (`CATEGORIE_DE_LA_PLACE`) REFERENCES `categorie_place`(`CATEGORIE_DE_LA_PLACE`);
ALTER TABLE `tarif` ADD FOREIGN KEY (`CATEGORIE_DE_LA_SEANCE`) REFERENCES `categorie_seance`(`CATEGORIE_DE_LA_SEANCE`);
ALTER TABLE `tarif` ADD FOREIGN KEY (`CATEGORIE_DE_LA_PLACE`) REFERENCES `categorie_place`(`CATEGORIE_DE_LA_PLACE`);
ALTER TABLE `seance` ADD FOREIGN KEY (`PROJETER`) REFERENCES `film`(`NUMERO_FILM`);
ALTER TABLE `seance` ADD FOREIGN KEY (`A_POUR_CATEGORIE`) REFERENCES `categorie_seance`(`CATEGORIE_DE_LA_SEANCE`);



-- ecrire un déclencheur (Trigger) qui lorsque l’on réalise une réservation sur la place n°1, le fait puis change la catégorie de la place en  catégorie spéciale. Vérifier le fonctionnement du déclencheur.

-- DELIMITER $$
-- CREATE TRIGGER `place_speciale` BEFORE INSERT ON `reservation` FOR EACH ROW
-- BEGIN
--     IF NEW.NUMERO_PLACE = 1 THEN
--         UPDATE place SET CATEGORIE_DE_LA_PLACE = 2 WHERE NUMERO_PLACE = 1;
--     END IF;
-- END$$

-- INSERT INTO `reservation` (`NUMERO_SEANCE`, `NOM_SPECTATEUR`, `NUMERO_PLACE`) VALUES ('1', 'Jean', '22');

